import { PrismaClient } from "../../src/generated/prisma";

export async function main(prisma: PrismaClient) {
  const rewardsData = [
    {
      xpLevel: 4,
      xpPointsToNext: 90,
      xpCurrentPoints: 45,
      rank: "Bronze",
      nextRankUnlockLevel: 5,
      points: 180,
      userId: "user-1-id",
    },
    {
      xpLevel: 5,
      xpPointsToNext: 100,
      xpCurrentPoints: 50,
      rank: "Gold",
      nextRankUnlockLevel: 6,
      points: 200,
      userId: "user-2-id",
    },
    {
      xpLevel: 3,
      xpPointsToNext: 80,
      xpCurrentPoints: 40,
      rank: "Silver",
      nextRankUnlockLevel: 4,
      points: 120,
      userId: "user-3-id",
    },
    {
      xpLevel: 2,
      xpPointsToNext: 60,
      xpCurrentPoints: 20,
      rank: "Bronze",
      nextRankUnlockLevel: 3,
      points: 60,
      userId: "user-4-id",
    },
    {
      xpLevel: 7,
      xpPointsToNext: 150,
      xpCurrentPoints: 90,
      rank: "Platinum",
      nextRankUnlockLevel: 8,
      points: 350,
      userId: "user-5-id",
    },
    {
      xpLevel: 6,
      xpPointsToNext: 120,
      xpCurrentPoints: 60,
      rank: "Gold",
      nextRankUnlockLevel: 7,
      points: 240,
      userId: "user-6-id",
    },
    {
      xpLevel: 2,
      xpPointsToNext: 50,
      xpCurrentPoints: 25,
      rank: "Bronze",
      nextRankUnlockLevel: 3,
      points: 70,
      userId: "user-7-id",
    },
    {
      xpLevel: 8,
      xpPointsToNext: 200,
      xpCurrentPoints: 100,
      rank: "Diamond",
      nextRankUnlockLevel: 9,
      points: 400,
      userId: "user-8-id",
    },
    {
      xpLevel: 3,
      xpPointsToNext: 80,
      xpCurrentPoints: 40,
      rank: "Silver",
      nextRankUnlockLevel: 4,
      points: 130,
      userId: "user-9-id",
    },
    {
      xpLevel: 5,
      xpPointsToNext: 110,
      xpCurrentPoints: 55,
      rank: "Gold",
      nextRankUnlockLevel: 6,
      points: 210,
      userId: "user-10-id",
    },
    {
      xpLevel: 4,
      xpPointsToNext: 90,
      xpCurrentPoints: 45,
      rank: "Bronze",
      nextRankUnlockLevel: 5,
      points: 180,
      userId: "user-11-id",
    },
    {
      xpLevel: 2,
      xpPointsToNext: 60,
      xpCurrentPoints: 30,
      rank: "Bronze",
      nextRankUnlockLevel: 3,
      points: 80,
      userId: "user-12-id",
    },
    {
      xpLevel: 7,
      xpPointsToNext: 160,
      xpCurrentPoints: 80,
      rank: "Platinum",
      nextRankUnlockLevel: 8,
      points: 360,
      userId: "user-13-id",
    },
    {
      xpLevel: 5,
      xpPointsToNext: 100,
      xpCurrentPoints: 50,
      rank: "Gold",
      nextRankUnlockLevel: 6,
      points: 200,
      userId: "user-14-id",
    },
    {
      xpLevel: 3,
      xpPointsToNext: 80,
      xpCurrentPoints: 40,
      rank: "Silver",
      nextRankUnlockLevel: 4,
      points: 120,
      userId: "user-15-id",
    },
  ];

  for (const data of rewardsData) {
    await prisma.rewards.create({ data });
  }
}

// Note: main() is now called from mainSeeder.ts
